name: Terraform

on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        required: true
      tf_workspace_name:
        type: string
        required: true
      environment:
        description: "Deployment environment (optional)"
        required: false
        type: string
  
jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: ${{inputs.tf_workspace_name}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform plan
        run: |
          echo "hello plan ${TF_WORKSPACE}"


  apply:
    if: false
    environment: ${{inputs.environment}}
    needs: plan
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: ${{inputs.tf_workspace_name}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform apply
        run: |
          echo "hello apply ${TF_WORKSPACE}"
          echo "environment: '${{inputs.environment}}'"
