name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  terraform:
    uses: cetv26/provisioning-envs-public/.github/workflows/reusable-workflow.yml@main
    secrets: inherit
    with:
      working_directory: terraform/env/dev
      tf_workspace_name: terraform-dev
      environment: test
