name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    uses: cetv26/common-workflows/.github/workflows/terraform.yml@main
    secrets: inherit
    with:
      working_directory: terraform/env/dev
      tf_workspace_name: terraform-dev        
